### PR TITLE
Custom Super Tokens V3

### PR DESCRIPTION
**Pull request by youssefea**
This version does the following:
- Make the project mono-framework compatible with Foundry
- Add Pure Super Token as an example and simple tests
- Add BridgedSuperToken and OPBridgedSuperToken examples with tests

Everything runs smoothly through `forge install` and `forge test --via-ir`

### CODE REVIEW

**Comment by hellwolf** [comment]
- Please completely remove the truffle usage.
- After removing truffle, consider to keep it mono-framework to keep the example simpler to copy over.

**Comment by hellwolf** [comment]
out folder is commited to the repo

**Comment by youssefea** [comment]
@hellwolf please don't merge yet. It's WIP. I'll ping you when done

**Comment by hellwolf** [comment]
converted to draft.

**Comment by youssefea** [comment]
@hellwolf ready for review and merge

**Review by hellwolf — CHANGES_REQUESTED** [review]
image

these should be submodules

**Comment by d10r** [comment]
I did a few changes:
* make it work without via-ir (which slows down a lot) and removed the readme section about it (since it's nothing specific to this repo, nor required knowledge anymore)
* updated to Solidity 0.8.26 to be in sync with protocol-monorepo
* removed custom UUPSProxy (there's no good reason to not use that in protocol-monorepo)
* moved xerc20 related contracts to a subdirectory (I think that makes it easier to understand the repo)
* some code polishing especially around imports
* revised the readme

@youssefea if it's fine for you as is, go ahead and merge!

**Review by d10r — APPROVED** [review]

**Comment by d10r** [comment]
PS: I assume .npmignore is to be removed too. Maybe also .prettierrc ?

**Review by hellwolf — APPROVED** [review]

**Pull request merged**
